Tuan5_NguyenVanTuan/Controllers/SachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tuan5_NguyenVanTuan.Models;

namespace Tuan5_NguyenVanTuan.Controllers
{
    public class SachController : Controller
    {
        MyDataDataContext data = new MyDataDataContext();
        // GET: Sach
        public ActionResult ListSach()
        {
            var all_sach = from ss in data.Saches select ss;
            return View(all_sach);
        }
        public ActionResult Detail(int id)
        {
            var D_sach = data.Saches.Where(m => m.masach == id).First();
            return View(D_sach);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(FormCollection collection, Sach s)
        {
            var E_tensach = collection["tensach"];
            var E_hinh = collection["hinh"];
            var E_giaban = Convert.ToDecimal(collection["giaban"]);
            var E_ngaycapnhat = Convert.ToDateTime(collection["ngaycapnhat"]);
            var E_soluongton = Convert.ToInt32(collection["soluongton"]);
            if (string.IsNullOrEmpty(E_tensach))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                s.tensach = E_tensach.ToString();
                s.hinh = E_hinh.ToString();
                s.giaban = E_giaban;
                s.ngaycapnhat = E_ngaycapnhat;
                s.soluongton = E_soluongton;
                data.Saches.InsertOnSubmit(s);
                data.SubmitChanges();
                return RedirectToAction("ListSach");
            }
            return this.Create();
        }
        public ActionResult Edit(int id)
        {         
            var E_sach = data.Saches.First(m => m.masach == id);
            return View(E_sach);
        }
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            var E_sach = data.Saches.First(m => m.masach == id);
            var E_tensach = collection["tensach"];
            var E_hinh = collection["hinh"];
            var E_giaban = Convert.ToDecimal(collection["giaban"]);
            var E_ngaycapnhat = Convert.ToDateTime(collection["ngaycatnhat"]);
            var E_soluongton = Convert.ToInt32(collection["soluongton"]);
            E_sach.masach = id;
            if (string.IsNullOrEmpty(E_tensach))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                E_sach.tensach = E_tensach;
                E_sach.hinh = E_hinh;
                E_sach.giaban = E_giaban;
                E_sach.ngaycapnhat = E_ngaycapnhat;
                E_sach.soluongton = E_soluongton;
                UpdateModel(E_sach);
                data.SubmitChanges();
                return RedirectToAction("ListSach");
            }
            return this.Edit(id);
        }
        //-----------------------------------------
        public ActionResult Delete(int id)
        {
            var D_sach = data.Saches.First(m => m.masach == id);
            return View(D_sach);
        }
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            var D_sach = data.Saches.Where(m => m.masach == id).First();
            data.Saches.DeleteOnSubmit(D_sach);
            data.SubmitChanges();
            return RedirectToAction("ListSach");
        }
        public string ProcessUpload(HttpPostedFileBase file)
        {
            if (file == null)
            {
                return "";
            }

            file.SaveAs(Server.MapPath("~/Content/images/" + file.FileName));

            return "/Content/images/" + file.FileName;
        }

    }
}

Tuan5_NguyenVanTuan/Views/Sach/Create.cshtml
@model Tuan5_NguyenVanTuan.Models.Sach

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Sach</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.maloai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.maloai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.maloai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tensach, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tensach, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tensach, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.hinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.hinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.hinh, "", new { @class = "text-danger" })
                <input type="file" name="fileUpload" id="fileUpload" accept="image/*" style="display:none;" />
                <input type="button" id="btnUpload" value="Chọn" class="btn btn-success" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.giaban, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.giaban, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.giaban, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ngaycapnhat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ngaycapnhat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ngaycapnhat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.soluongton, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.soluongton, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.soluongton, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("ListSach", "ListSach", "Sach")
</div>
@section upload
 {
    <script>
        $(function () {
            $('#btnUpload').click(function () {
                $('#fileUpload').trigger('click');
            });
        });

        $('#fileUpload').change(function () {
            if (window.FormData !== undefined) {
                var fileUpload = $('#fileUpload').get(0);
                var files = fileUpload.files;
                var formData = new FormData();
                formData.append('file', files[0]);
                $.ajax(
                    {
                        type: 'POST',
                        url: '/Sach/ProcessUpload',
                        contentType: false,
                        processData: false,
                        data: formData,
                        success: function (urlImage) {
                            $('#pictureUpload').attr('src', urlImage);
                            $('#hinh').val(urlImage);
                        },
                        error: function (err) {
                            alert('Error ', err.statusText);
                        }
                    });
            }
        });
    </script>
}

Tuan5_NguyenVanTuan/Views/Sach/Delete.cshtml
@model Tuan5_NguyenVanTuan.Models.Sach

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sach</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.maloai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.maloai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tensach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tensach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.giaban)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.giaban)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ngaycapnhat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngaycapnhat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.soluongton)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.soluongton)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Tuan5_NguyenVanTuan/Views/Sach/Detail.cshtml
@model Tuan5_NguyenVanTuan.Models.Sach

@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detail</h2>

<div>
    <h4>Sach</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
           Mã Loại:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.maloai)
        </dd>

        <dt>
            Tên sách :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tensach)
        </dd>        
        <dt>
            Hình:
        </dt>

        <dd>
            <img src="@Html.DisplayFor(modelItem => Model.hinh)" style="width:150px; height:200px;" />
        </dd>

        <dt>
            Giá Bán:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.giaban)
        </dd>

        <dt>
            Ngày Cập Nhật:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngaycapnhat)
        </dd>

        <dt>
            Số Lượng Tồn:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.soluongton)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.masach }) |
    @Html.ActionLink("ListSach", "ListSach", "Sach")
</p>

Tuan5_NguyenVanTuan/Views/Sach/Edit.cshtml
@model Tuan5_NguyenVanTuan.Models.Sach

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Sach</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.masach)

        <div class="form-group">
            @Html.LabelFor(model => model.maloai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.maloai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.maloai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tensach, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tensach, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tensach, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10" style="margin-left:16.5%">
                <strong>Hình</strong>
                @Html.EditorFor(model => model.hinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.hinh, "", new { @class = "text-danger" })
                <input type="file" name="fileUpload" id="fileUpload" accept="image/*" style="display:none;" />
                <input type="button" id="btnUpload" value="Chọn" class="btn btn-success" />
                <img src="@Model.hinh" id="pictureUpload" />
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.giaban, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.giaban, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.giaban, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ngaycapnhat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ngaycapnhat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ngaycapnhat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.soluongton, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.soluongton, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.soluongton, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section upload
 {
    <script>
        $(function () {
            $('#btnUpload').click(function () {
                $('#fileUpload').trigger('click');
            });
        });

        $('#fileUpload').change(function () {
            if (window.FormData !== undefined) {
                var fileUpload = $('#fileUpload').get(0);
                var files = fileUpload.files;
                var formData = new FormData();
                formData.append('file', files[0]);
                $.ajax(
                    {
                        type: 'POST',
                        url: '/Sach/ProcessUpload',
                        contentType: false,
                        processData: false,
                        data: formData,
                        success: function (urlImage) {
                            $('#pictureUpload').attr('src', urlImage);
                            $('#hinh').val(urlImage);
                        },
                        error: function (err) {
                            alert('Error ', err.statusText);
                        }
                    });
            }
        });
    </script>
}

Tuan5_NguyenVanTuan/Views/Sach/ListSach.cshtml
@model IEnumerable<Tuan5_NguyenVanTuan.Models.Sach>
@{
    ViewBag.Title = "ListSach";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ListSach</h2>
<h2>THÔNG TIN SÁCH</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th> Mã loại </th>
        <th> Tên sách</th>
        <th> Hình </th>
        <th> Giá bán</th>
        <th> Ngày cập nhật </th>
        <th> Số lượng tồn</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.maloai)</td>
            <td>@Html.DisplayFor(modelItem => item.tensach)</td>
            <td><img src="@item.hinh" alt="hinh thumbnail" /></td>
            <td>@Html.DisplayFor(modelItem => item.giaban)</td>
            <td>@Html.DisplayFor(modelItem => item.ngaycapnhat)</td>
            <td>@Html.DisplayFor(modelItem => item.soluongton)</td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.masach }) |
                @Html.ActionLink("Detail", "Detail", new { id = item.masach }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.masach })
            </td>
        </tr>
    }
</table>